spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ABCabc123#
    url: jdbc:mysql://localhost:3306/db_test?useSSL=false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql